"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
command_timeout = 3000
palette = "srcery"

format = """$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$golang\
$nodejs\
$php\
$python\
$rust\
$memory_usage\
$sudo\
$cmd_duration\
$jobs\
$battery\
$time\
$status\
$character"""

[battery]
disabled = false
full_symbol = "󰁹 "
charging_symbol = "󰂄 "
discharging_symbol = "󰂃 "

[[battery.display]]
threshold = 50

[character]
success_symbol = "[›](color_green)"
error_symbol = "[›](color_red)"
vimcmd_symbol = "[‹](color_magenta)"

[cmd_duration]
min_time = 3_000
format = "[󱎫 $duration]($style)"

[directory]
read_only = " 󰌾"
style = "color_blue"
truncation_length = 2
fish_style_pwd_dir_length = 1

[git_branch]
symbol = "󰘬"
style = "color_brightblack"
format = "[$symbol $branch(:$remote_branch)]($style) "

[git_commit]
tag_symbol = '  '

[git_metrics]
disabled = false
format = '([↑$added]($added_style) )([↓$deleted]($deleted_style) )'
only_nonzero_diffs = true
added_style = "color_green"
deleted_style = "color_red"

[git_status]
style = "color_teal"
format = "([\\[$all_status$ahead_behind\\]]($style) )"
conflicted = "✖"
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
untracked = "…${count}"
stashed = "󰏗"
modified = "✚${count}"
staged = "●${count}"
renamed = "󰁕${count}"
deleted = "󰆴${count}"

[golang]
symbol = "󰟓"
format = "[$symbol]($style) "

[hostname]
ssh_symbol = "󰣀 "

[memory_usage]
symbol = "󰍛 "

[nodejs]
symbol = "󰎙"
format = "[$symbol]($style) "

[php]
symbol = "󰌟"
format = "[$symbol]($style) "

[python]
symbol = "󰌠"
format = "[${symbol}${pyenv_prefix}($virtualenv)]($style) "

[status]
symbol = "× "
disabled = false

[palettes.srcery]
color_bg0 = "#1c1b19"
color_bg1 = "#121212"
color_blue = "#2c78bf"
color_brightblack = "#918175"
color_brightblue = "#68a8e4"
color_brightcyan = "#2be4d0"
color_brightgreen = "#98bc37"
color_brightmagenta = "#ff5c8f"
color_brightorange = "#ff8700"
color_brightred = "#f75341"
color_brightyellow = "#fed06e"
color_fg0 = "#fce8c3"
color_green = "#519f50"
color_magenta = "#e02c6d"
color_orange = "#ff5f00"
color_red = "#ef2f27"
color_teal = "#008080"
color_xgray1 = "#262626"
color_yellow = "#fbb829"
